version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: database_service
    environment:
      POSTGRES_PASSWORD: hashpass
      POSTGRES_USER: hashusername
      POSTGRES_DB: hash_challenge
    networks:
      - database_network
    expose:
      - 5432
    ports:
      - 5431:5432
    restart: always

  api:
    depends_on:
      - db
    build:
      context: api/
      dockerfile: Dockerfile
    container_name: node_client
    ports:
      - 8080:8080
    tty: true
    networks:
      - database_network

  server:
    depends_on:
      - db
    build:
      context: grpc_server/
      dockerfile: Dockerfile
    container_name: python_server
    expose:
      - 50051
    ports: 
      - 50052:50051
    tty: true
    networks:
      - database_network

networks:
  database_network:
    driver: bridge