version: '3.9'

services:
  db:
    build:
      context: shared-db/
      dockerfile: Dockerfile
    container_name: database_service
    networks:
      - database_network
    expose:
      - 5432
    restart: always

  api:
    depends_on:
      - db
    build:
      context: grpc-client-api-microservice/
      dockerfile: Dockerfile
    container_name: node_client
    ports:
      - 8080:8080
    tty: true
    networks:
      - database_network

  server:
    depends_on:
      - db
    build:
      context: grpc-server-microservice/
      dockerfile: Dockerfile
    container_name: python_server
    expose:
      - 50051
    tty: true
    networks:
      - database_network

networks:
  database_network:
    driver: bridge