#!/bin/bash
Help()
{
   echo "Run script options:"
   echo "up             run docker-compose up -d --build"
   echo "down           down docker-compose and remove containers, networks, images and volumes"
   echo "tests          run gRPC Python Server tests and gRPC Node Client tests"
   echo "downserver     down gRPC Python Server"
   printf "\n"
}

up()
{
    docker-compose up -d --build
}

down()
{
    docker-compose down &&\
    docker image rm desafio_hash_server desafio_hash_api
}

tests()
{
    echo "[Running gRPC Python Server Tests]"
    docker exec -it python_server sh -c "py.test"

    echo "[Running gRPC Python Unit Tests]"
    docker exec -it python_server sh -c "python3 -m unittest"

    echo "==================================================== gRPC Client ============================================================"
    echo "[Running gRPC Node Client E2E Tests]"
    docker exec -it node_client sh -c "npm run test"
}

downserver()
{
    docker-compose stop server
}

HASH_CHALLENGE_SCRIPT_ACTION=$1

if [ -z "$HASH_CHALLENGE_SCRIPT_ACTION" ]
    then Help
else
    if [ "$HASH_CHALLENGE_SCRIPT_ACTION" = "up" ]
        then down; up
    elif [ "$HASH_CHALLENGE_SCRIPT_ACTION" = "down" ]
        then down
    elif [ "$HASH_CHALLENGE_SCRIPT_ACTION" = "tests" ]
        then tests
    elif [ "$HASH_CHALLENGE_SCRIPT_ACTION" = "downserver" ]
        then downserver
    fi
fi