#!/bin/bash
echo "Generating Migration Table"
# ts-node ./node_modules/.bin/typeorm migration:run
ts-node ./node_modules/.bin/typeorm migration:generate -n tables
echo "Sync Schemas..."
ts-node ./node_modules/.bin/typeorm schema:sync

echo "Configuring Seeding Files"
ts-node ./node_modules/typeorm-seeding/dist/cli.js config
echo "Running Seeders..."
ts-node ./node_modules/typeorm-seeding/dist/cli.js seed

echo "Running Server"
npm start
